default:
  app_name: "shinyMirage"
  version: "v0.1.0"
  logo: "logoAnn.png"
  report: "reports/reportAnn.pdf"

main:
  app_name: "shinyMirage"
  version: "v0.1.0"
  logo: "logoAnn.png"
  report: "reports/reportAnn.pdf"

progenika:
  app_name: "shinyMirage - Progenika"
  version: "v0.1.0-Progenika"
  logo: "logoGrifols.png"
  report: "reports/reportProgenika.pdf"

werfen:
  app_name: "shinyMirage - Werfen"
  version: "v0.1.0-Werfen"
  logo: "logoWerfen.png"
  report: "reports/reportWerfen.pdf"
